name: Src QA 🔎
run-name: src-qa 🔎
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize, labeled]
    branches: [development]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BASE_BRANCH: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

permissions:
    checks: write
    pull-requests: write

jobs:
  compile:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: TypesScript Compilation
        run: npm run type-check

  linting:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.BASE_BRANCH }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          eslint_flags: "cypress --ext .ts,.tsx,.js,.jsx --max-warnings 0"
          fail_level: error

  knip-dev:
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: knip.dev
        uses: codex-/knip-reporter@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment_id: "Knip.dev-✂️"
          annotations: false
          verbose: true
